[api]
  debug = true
  dashboard = true

[accessLog]

[entryPoints]
  [entryPoints.web]
    address = ":80"

    # [entryPoints.web.http]
    #     [entryPoints.web.http.redirections]
    #     [entryPoints.web.http.redirections.entryPoint]
    #         to = "ssl"
    #         scheme = "https"


  [entryPoints.ssl]
    address = ":443"

[providers.docker]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true

# traefik.toml
[providers.file]
  directory = "/etc/ssl-keys/"
